# Generated by Django 5.2.7 on 2025-10-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('experiencia', models.PositiveIntegerField()),
                ('idiomas', models.TextField()),
                ('especialidad', models.CharField(max_length=100)),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
